import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="h-screen bg-neutral-50">
      <Head>
        <title>MWS Registration | Home</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <main className="flex flex-col items-center pt-6">
        <h1 className="text-4xl">
          Welcome to
          {" "}
          <a
            className="text-purple-500 hover:underline decoration-purple-500"
            target="_blank"
            rel="noreferrer"
            href="https://mobilewaves.com/">
            Mobile Waves!
          </a>
        </h1>
        <Link href="/registration/step-1">
          <a className="mt-8 px-4 py-2 text-white bg-rose-500 rounded" role="button">
            Register
          </a>
        </Link>
      </main>
    </div>
  )
}

export default Home
